export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ContactPage } from './ContactPage'
export { default as StructuralDesignPage } from './StructuralDesignPage'
export { default as DraftingServicesPage } from './DraftingServicesPage'
export { default as SiteSupervisionPage } from './SiteSupervisionPage'
export { default as StructuralAuditPage } from './StructuralAuditPage'
